In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
df=pd.read_csv("/content/Reviews.csv", on_bad_lines='skip', engine='python')

In [11]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


In [16]:
print("Shape :", df.shape)

Shape : (1114646, 10)


In [17]:
light_reviews = df[df["Text"].str.contains(r"\blight\b", case=False, na=False)]

print("Total reviews containing 'light':", len(light_reviews))

Total reviews containing 'light': 30275


In [18]:
for i, text in enumerate(light_reviews["Text"].head(100)):
     print(f"\nReview {i}\n")
     print(text)


Review 0

This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 1

A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a few miles away. The current deal for th

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1114646 entries, 0 to 1114645
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype 
---  ------                  --------------    ----- 
 0   Id                      1114646 non-null  object
 1   ProductId               1114642 non-null  object
 2   UserId                  1114639 non-null  object
 3   ProfileName             1114578 non-null  object
 4   HelpfulnessNumerator    1114609 non-null  object
 5   HelpfulnessDenominator  1114602 non-null  object
 6   Score                   1114599 non-null  object
 7   Time                    1114598 non-null  object
 8   Summary                 1114535 non-null  object
 9   Text                    1114572 non-null  object
dtypes: object(10)
memory usage: 85.0+ MB


In [22]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [23]:
sentence_1 = "This olive oil is wonderful and very light on the stomach."

sentence_2 = "The packaging was broken and let too much light inside the box."

sentence_3 = "I prefer this brand because it is a light and healthy snack."

sentences = [sentence_1, sentence_2, sentence_3]

In [24]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(sentences)

dense_matrix = X.toarray()

print("\nVocabulary")
print(vectorizer.get_feature_names_out())

print("\nDense Matrix")
print(dense_matrix)


Vocabulary
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

Dense Matrix
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [25]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]


In [26]:
print(vec_1)
print()
print(vec_2)
print()
print(vec_3)

[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]

[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]

[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [27]:
similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

In [28]:
print("\nSimilarity Scores")

print("Sentence 1 vs Sentence 2 :", similarity_1_2)

print("Sentence 1 vs Sentence 3 :", similarity_1_3)


Similarity Scores
Sentence 1 vs Sentence 2 : 4
Sentence 1 vs Sentence 3 : 4
